name: Keep Streamlit Alive

on:
  schedule:
    # Her 3 günde bir çalışır
    - cron: '0 0 */3 * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -s https://chobea.streamlit.app > /dev/null
